In [ ]:
import numpy as np

In [ ]:
o = np.array([[1,2,3],[4,5,6]])
print(o)
print(o.ndim)    #no of axis or dimensions
print(o.shape)   #no of row * columns in array
print(o.size)    #total no of elements in array

**Create different dimensional arrays**

In [ ]:
a = np.array([1,2,3,4])  #Creating an 1-D array
print(a)
print(a.shape)

In [ ]:
b = np.array([[1,2],[3,4]])  #Creating an 2-D array
print(b)
print()
b1 = np.array([[3,4]])     #Creating an 2-D array
print(b1)
print(b1.ndim)

In [ ]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])  #Creating an 3-D array
print(c)
print()
c1 = np.array([[[7,8,9]]])  #Creating an 3-D array
print(c1)
print(c1.ndim)

In [ ]:
c1 = np.array([1,2,3,4,5],ndmin=10)           #Creating an n-D array
print(c1)

In [ ]:
l = [i for i in range(0,11)]  #Printing the series of array using range()
d = np.array(l)
print(d)

e = np.arange(0,11)    #Printing the series of array using arange()
print(e)

In [ ]:
d = np.eye(4)      #creates an diagonal array with no of given 1's given in row place of eye() function
print(d)
print()
d1 = np.eye(3,4)      #creates an diagonal array with no of given 1's given in row place eye() function
print(d1)

In [ ]:
e = np.tile([1,2,3],4)         #creates a new array by repeating an existing array for a particular number of times i.e., 4 times here
print(e)

In [ ]:
f = np.full((3,2),5)         #creates an array of given shape(3,2) and with the element given
print(f)

In [ ]:
z = np.zeros(4,dtype = int)    #Creating a 1-D array with 0's
print(z)
print()
z1 = np.zeros((2,3))   #Creating a 2-D array with 0's
print(z1)
print()
z2 = np.zeros((3,3))   #Creating a 3-D array with 0's
print(z2)
print()
z3 = np.zeros((2,3,3))   #Creating 2 3-D arrays with 0's
print(z3)

In [ ]:
o = np.ones(4,dtype = int)    #Creating a 1-D array with 1's
print(o)
print()           #if datatype is not mentioned float is default
o1 = np.ones((2,2))    #Creating a 2-D array with 1's
print(o1)
print()
o2 = np.ones((3,3))    #Creating a 3-D array with 1's
print(o2)

In [ ]:
e = np.empty(4)      #Creating a empty array
print(e)             #it stores the memory from cache

In [ ]:
g = np.linspace(0,20,5)   #Creating a vector on line scape
print(g)
print()
g1 = np.linspace(0,10,5)   #Creating a vector on line scape
print(g1)

**Random Functions**

In [ ]:
#Random Functions
var = np.random.rand(4)    #Creates an array with 4 elements between 0 to 1 randomly only +ve
print(var)
print()
var1 = np.random.rand(2,5)    #Creates an array with 2*5 = 10 elements between 0 and 1 randomly only +ve
print(var1)
print()
var2 = np.random.randn(4)    #Creates an array with 4 elements between 0 and 1 randomly close to 0 and 1 includes +ve and -ve
print(var2)
print()
var3 = np.random.ranf(4)    #Creates an array with 4 elements between 0 and 1(not 1) randomly -- float numbers only +ve
print(var3)
print()
var4 = np.random.randint(low = 4,high = 10,size = 10)    #Creates an array with 10 elements between 4 and 10 randomly -- randint(start,end,no of numbers in array)
print(var4)

**Arithmatic Operations**

In [ ]:
#Arithmatic Operation in 1-D Arrays
var = np.array([1,2,3,4])
print(var + 3)   #direct addition
print(np.add(var,3))    #using add() of numpy module
print()
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = a + b
print(c)
print(np.add(a,b))

#Similarly we can use - * / % ** as subtract(),multiply(),divide(),mod(),power() respectively

In [ ]:
#Arithmatic Operation in 2-D Arrays
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print()
b = np.array([[10,2,3,4],[15,6,7,1]])
print(b)
print()
c = np.add(a,b)
print(c)

In [ ]:
m = np.array([1,2,3,4,5])  #Multiplication with 3
print(m * 3)

In [ ]:
x = np.array([-2,-1,0,1,2])
print(abs(x))            #absolute function
print(np.absolute(x))

In [11]:
a = np.arange(1,10).reshape(3,3)
print(a)
print()
print(np.fliplr(a))    #produces a mirror image
print()
print(np.flipud(a))
print()
print(a.transpose())
print()
print(np.flipud(a.transpose()))
print()
print(np.rot90(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[3 2 1]
 [6 5 4]
 [9 8 7]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[3 6 9]
 [2 5 8]
 [1 4 7]]

[[3 6 9]
 [2 5 8]
 [1 4 7]]


**Trigonometric Functions**

In [ ]:
np.pi

In [ ]:
theta = np.linspace(0,np.pi,5)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

**Exponential and Logarthmic Functions**

In [ ]:
x = np.array([1,2,3,10])
print(x)
print(np.exp(x))   #[e**1,e**2,e**3,e**10]   where e=2.74)
print(np.exp2(x))  #[2**1,2**2,2**3,2**10]
print(np.power(x,3))
print(np.power(x,2))

In [ ]:
print(np.log(x))     #log x
print(np.log2(x))
print(np.log10(x))

In [ ]:
#Aggregate functions
x = np.array([1,2,3,4,5])
print(np.add.reduce(x))
print(np.add.accumulate(x))
print(np.subtract.reduce(x))
print(np.multiply.reduce(x))
print(np.multiply.accumulate(x))

**Statistical Functions**

In [ ]:
#Some statistical functions
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.min(a))  #Complete array
print(np.min(a,axis=0)) #Column wise
print(np.min(a,axis=1)) #Row wise
#Similarly np.max(a) can also be used

print()
print(np.min(a),np.max(a),np.argmin(a),np.argmax(a))  #argmin() -- gives the position of min element  #argmax() -- gives the position of max element
print(np.sqrt(a))   #Square root of array elements

In [ ]:
import numpy as np
n = np.array([1,2,3,4,5,6,7,8,9])   #Statistical functions
print(n.max())
print(n.min())
print(n.sum())
print(n.mean())
print(np.median(n))
print(n.std())

**Shape and Re-Shape in Numpy Arrays**

In [ ]:
arr1 = np.array([1,2,3,4],ndmin=4)
print(arr1)
print("Ndim:",arr1.ndim)       #ndim gives no of axis or dimensions of an array
print("Shape:",arr1.shape)     #Shape function gives the no of rows and columns in array
print()
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print("Ndim:",arr2.ndim)       #ndim gives no of axis or dimensions of an array
print("Shape:",arr2.shape)     #Shape function gives the no of rows and columns in array

In [ ]:
import numpy as np
a1 = np.array([1,2,3,4,5,6])
print(a1)
print(a1.ndim)
print()
a2 = a1.reshape(3,2)
print(a2)
print(a2.ndim)
print()
a3 = a1.reshape(2,3)
print(a3)
print(a3.ndim)
print()

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
i = arr1.reshape((3,3))
#i = np.reshape(arr1,(3,3))   #Re-shaping the 1-D to 3-D array
print(i)
print(i.ndim)
j = np.reshape(i,-1)   #Re-shaping the 3-D to 1-D array
print(j)
print(i.flatten())    #Re-shaping the 3-D to 1-D array using flatten method

In [ ]:
u = np.array([1,2,3,4,5,6,7,8,9,10,11,12])   #Re-shaping the array
a1 = np.reshape(u,(4,3))
print(a1)
a2 = np.reshape(u,(2,3,2))
print(a2)
a3 = np.reshape(a2,-1)
print(a3)

**Broadcasting in Arrays**

In [ ]:
x = np.array([[1],[2]])
print(x)
print(x.shape)   #(2,1)
print()
y = np.array([[1,2,3],[1,2,3]])
print(y)
print(y.shape)   #(2,3)
print()
# so there is 1 in RHS of shape in atleast one shapes between x and y
#addition is possible
z = x+y
print(z)
print(z.shape)   #max(x.shape,y.shape) -- (2,3)

In [ ]:
x = np.array([1,2,3])
print(x)
print(x.shape)   #(1,3)
print()
y = np.array([[1],[2],[3]])
print(y)
print(y.shape)   #(3,1)
print()
# so there is 1 in RHS of shape in atleast one shapes between x and y
#addition is possible
z = x+y
print(z)
print(z.shape)   #max(x.shape,y.shape) -- (3,3)

**Slicing and Indexing**

In [ ]:
arr1 = np.array([1,2,3,4])   #Indexing 1-D matrix
print(arr1)
print(arr1[0])

In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])   #Indexing 2-D matrix
print(arr2)
print(arr2[0][2])
print(arr2[1][1])
print(arr2[0,1])

In [ ]:
p = np.array([[1,2,3,4],[5,6,7,8]])  #Indexing 2-D matrix
print(p[0,1])
print(p[1,2])
print(p[1,-1])
print(p[1,1:3])
print(p[0:2,2])
print(p[0:2,1:3])

In [ ]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])   #Indexing 3-D matrix
print(arr3)
print(arr3[0][1][1])
print(arr3[1][0][0])
print(arr3[0,1,0])

In [ ]:
k = np.arange(20)   #Slicing 1-D matrix
print(k)
print(k[1:10:2])

arr1 = np.array([1,2,3,4])   #Slicing 1-D matrix
print(arr1)
print(arr1[0:2])

In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])   #Slicing 2-D matrix
print(arr2)
print()
print(arr2[0,0:3])
print()
print(arr2[0:3,1])
print()
print(arr2[0:3,0:3])    #1st 3 rows and 1st 3 columns


l = np.array([[1,2,3], [3,4,5], [4,5,6]])   #Slicing sub-matrices
print(l)
print(l[0:2, 0:2]) #1st 2 rows and 1st 2 columns

**Iteration in Arrays**

In [ ]:
v = np.array([[1,2,3],[4,5,6]])    #Iterating the 2-D Matrix -- no. of axis == no. of for loops
for x in v:
  for y in x:
    print(y)

In [ ]:
w = np.array([[[1,2,3],[4,5,6],[7,8,9]]])   #Iterating the 3-D Matrix -- no. of axis == no. of for loops
for x in w:
  for y in x:
    for i in y:
      print(i)

In [ ]:
v = np.array([[1,2,3],[4,5,6]])      #Iterating the 2-D Matrix
print(v)
for x in np.nditer(v):          #using nditer() we can avoid usage of multiple for loops
  print(x)

In [ ]:
v = np.array([[1,2,3],[4,5,6]])      #Iterating the 2-D Matrix
print(v)
for x in np.ndenumerate(v):          #using ndenumerate() we can avoid usage of multiple for loops and we can its index also.
  print(x)

**Copy and view**

In [ ]:
x = np.array([1,2,3,4])          #Copy() method
c = x.copy()
x[0] = 10
print(x)     #Original Array
print(c)     #Copy method doesn't get affected by the changes done to the original array

In [ ]:
x = np.array([1,2,3,4])          #View() method
v = x.view()
x[0] = 10
print(x)     #Original Array
print(v)     #View method gets affected by the changes done to the original array

**Functions in Arrays**

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.concatenate((a,b),axis=0)       #Adding as rows -- default
print(c)

In [ ]:
s = np.array([[1,2],[3,4]])
t = np.array([[5,6]])
a = np.concatenate((s,t))
print(a)
a1 = np.concatenate((s,t),axis = 0)  #Adding as rows -- default
print(a1)
a2 = np.concatenate((s,t.T),axis = 1)  #Adding as columns   .T is nothing by transpose
print(a2)
a3 = np.concatenate((s,t),axis = None)  #Adding into single array
print(a3)

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a1 = np.stack((a,b),axis=0)       #Adding as rows -- default
print(a1)
a2 = np.stack((a,b),axis=1)       #Adding as columns -- default
print(a2)

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a2 = np.hstack((a,b))   #this works out when the no of rows are same
print(a2)
a3 = np.vstack((a,b))   #this works out when the no of columns are same
print(a3)
a4 = np.dstack((a,b))
print(a4)

In [ ]:
a = np.array([1,2,3,4])            #array_split()
print(a)
s = np.array_split(a,2)
print(s)
print(s[0])
print(s[0][0])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])    #array_split() is used to split the arrays
print(a)
s = np.array_split(a,2)
print(s)
print(s[0])
print(s[0][0])
print(s[0][0][0])

In [ ]:
a = np.array([1,2,3,4,2,3,2])            #searching in array using where() function
x = np.where(a==1)
print(x)
y = np.where(a==2)
print(y)
z = np.where((a%2)==0)
print(z)

In [ ]:
a = np.array([1,2,3,4,6,7,8])
x = np.searchsorted(a,5)      #gives the position of passed element in searchsorted() function using search
print(x)

In [ ]:
a = np.array([1,2,3,4,10,6,7,9,8])      #sorting
x = np.sort(a)
print(x)

b = np.array(['a','c','y','b'])
y = np.sort(b)
print(y)

In [ ]:
a = np.array([[4,10,6],[5,1,0]])      #sorting
print(a)
x = np.sort(a,axis=1)       #row-wise
print(x)
y = np.sort(a,axis=0)       #column wise
print(y)

In [ ]:
a = np.array([1,2,3,4,10,6,7,9,8])    #shuffling the data in array
np.random.shuffle(a)
print(a)

In [ ]:
a = np.array([1,2,3,4,10,6,1,2,3,4])     #deletes the duplicates
var = np.unique(a,return_index=True,return_counts=True)
print(var)

**Insert and Delete elements in Array**

In [ ]:
a = np.array([1,2,3,4])       #insert(arrayname,position/index no.,values)
v = np.insert(a,4,5)   #at position = 4
print(v)
v1 = np.insert(a,4,6.5)
print(v1)

In [ ]:
a = np.array([1,2,3,4])       #append(arrayname,values) -- adds at the end
v = np.append(a,5)   #at position = 4
print(v)
v1 = np.append(a,6.5)
print(v1)

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
v = np.insert(a,2,5,axis=0)     #Row wise
print(v)
print()
v1 = np.insert(a,4,5,axis=1)    #Column wise
print(v1)

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print()
v = np.insert(a,2,[9,10,11,12],axis = 0)     #Row wise
print(v)
print()
v1 = np.insert(a,4,[9,10],axis=1)    #Column wise
print(v1)

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])     #append() without any index no. adds at the end
v = np.append(a,[[9,10,11,12]],axis=0)     #Row wise
print(v)
print()
v1 = np.append(a,[[9],[10]],axis=1)    #Column wise
print(v1)

In [ ]:
a = np.array([1,2,3,4])       #delete(arrayname,position/index no.)
v = np.delete(a,2)   #at position = 2 -- axis is also used
print(v)

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
v = np.delete(a,2,axis=1)  #column-wise
print(v)
v1 = np.delete(a,1,axis=0)    #row-wise
print(v1)

**Matrices in Linear Algebra**

In [ ]:
help(np.linalg)

In [ ]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print(np.linalg.matrix_rank(a))
print(np.trace(a))
print(np.linalg.det(a))
#print(np.linalg.inv(a))   only non-singular matrix are allowed ie., det!=0
#print(np.matmul(array1,array2))   matrix multiplication
print(np.linalg.matrix_power(a,3))   #a.a.a   matrix multiplication

**Example Scenario:**
<pre>
Day 1
6 macbooks and 3 iPhones were sold for rs 27

Day 2
9 macbooks and 4 iPhones were sold for rs 38

find the price of each macbook and iPhone

In [12]:
# 6x + 3y = 27
# 9x + 4y = 38
# let us define coeff array
coeff = np.array (  [ [ 6,3] , [ 9, 4]] )
# define constants array
const = np.array  ( [ 27 , 38 ])

In [13]:
# numpy provides np.linalg.solve( ) for solving equations
result = np.linalg.solve( coeff , const)
# value of x and y
result

array([2., 5.])

# Quick Activity
---
<pre>
4a + 2b + 5c = 53
5a + 3b + 7c = 74
9a + 2b + 6c = 73

find the value of a,b and c

In [14]:
coeff = np.array ( [ [ 4, 2 , 5] , [ 5, 3, 7] , [9, 2, 6]] )
const = np.array ( [ 53 , 74, 73 ])
result = np.linalg.solve( coeff , const)
result

array([3., 8., 5.])

**Computational power between lists and numpy arrays**

In [ ]:
import time

l1 = [i for i in range(1,10000)]
l2 = [i**2 for i in range(1,10000)]

#time consumed when used lists
t0 = time.time()
product_list = list(map(lambda x,y: x*y,l1,l2))
t1 = time.time()
time_product_list = t1-t0
print('time consumed by product_list :',time_product_list)


#time consumed when used numpy arrays
a1 = np.array(l1)
a2 = np.array(l2)
t0 = time.time()
product_array = a1*a2
t1 = time.time()
time_product_array = t1-t0
print('time consumed by product_array:',time_product_array)

#This is the reason why the numpy arrays are prefered over lists.