### **Create different dimensional arrays**

In [1]:
import numpy as np

In [2]:
o = np.array([[1,2,3],[4,5,6]])
print(o)
print(o.ndim)    #no of axis or dimensions
print(o.shape)   #no of row * columns in array
print(o.size)    #total no of elements in array

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [92]:
a = np.array([1,2,3,4])  #Creating an 1-D array
print(a)
print(a.shape)
print()
a1 = np.array([8])
print(a1)

[1 2 3 4]
(4,)

[8]


In [85]:
b = np.array([[1,2],[3,4]])  #Creating an 2-D array
print(b)
print()
b1 = np.array([[3,4]])     #Creating an 2-D array
print(b1)
print(b1.ndim)
print(b1.shape)

[[1 2]
 [3 4]]

[[3 4]]
2
(1, 2)


In [5]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])  #Creating an 3-D array
print(c)
print()
c1 = np.array([[[7,8,9]]])  #Creating an 3-D array
print(c1)
print(c1.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

[[[7 8 9]]]
3


In [6]:
c1 = np.array([1,2,3,4,5],ndmin=10)           #Creating an n-D array
print(c1)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


In [9]:
l = [i for i in range(0,11)]  #Printing the series of array using range()
d = np.array(l)
print(d)

e = np.arange(0,11)    #Printing the series of array using arange()
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [10]:
d = np.eye(4)      #creates an diagonal array with no of given 1's given in row place of eye() function
print(d)
print()
d1 = np.eye(3,4)      #creates an diagonal array with no of given 1's given in row place eye() function
print(d1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [88]:
e = np.tile([1,2,3],4)         #creates a new array by repeating an existing array for a particular number of times i.e., 4 times here
print(e)
print(np.reshape(e,(4,3)))
print(type(e))

[1 2 3 1 2 3 1 2 3 1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [13]:
f = np.full((3,2),5)         #creates an array of given shape(3,2) and with the element given
print(f)

[[5 5]
 [5 5]
 [5 5]]


In [14]:
z = np.zeros(4,dtype = int)    #Creating a 1-D array with 0's
print(z)
print()
z1 = np.zeros((2,3))   #Creating a 2-D array with 0's
print(z1)
print()
z2 = np.zeros((3,3))   #Creating a 3-D array with 0's
print(z2)
print()
z3 = np.zeros((2,3,3))   #Creating 2 -- 3-D arrays with 0's
print(z3)

[0 0 0 0]

[[0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [17]:
o = np.ones(4,dtype = int)    #Creating a 1-D array with 1's
print(o)
print()           #if datatype is not mentioned float is default
o1 = np.ones((2,2))    #Creating a 2-D array with 1's
print(o1)
print()
o2 = np.ones((3,3))    #Creating a 3-D array with 1's
print(o2)
print()
o3 = np.ones((2,2,3))    #Creating 2 -- 3-D arrays with 1's
print(o3)

[1 1 1 1]

[[1. 1.]
 [1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [18]:
e = np.empty(4)      #Creating a empty array
print(e)             #it stores the memory from cache

[1. 1. 1. 1.]


In [19]:
g = np.linspace(0,20,5)   #Creating a vector on line scape
print(g)
print()
g1 = np.linspace(0,10,5)   #Creating a vector on line scape
print(g1)

[ 0.  5. 10. 15. 20.]

[ 0.   2.5  5.   7.5 10. ]


### **Random Functions**

In [20]:
#Random Functions
var = np.random.rand(4)    #Creates an array with 4 elements between 0 to 1 randomly only +ve
print(var)
print()
var1 = np.random.rand(2,5)    #Creates an array with 2*5 = 10 elements between 0 and 1 randomly only +ve
print(var1)
print()
var2 = np.random.randn(4)    #Creates an array with 4 elements between 0 and 1 randomly close to 0 and 1 includes +ve and -ve
print(var2)
print()
var3 = np.random.ranf(4)    #Creates an array with 4 elements between 0 and 1(not 1) randomly -- float numbers only +ve
print(var3)
print()
var4 = np.random.randint(low = 4,high = 10,size = 10)    #Creates an array with 10 elements between 4 and 10 randomly -- randint(start,end,no of numbers in array)
print(var4)

[0.73914862 0.57132248 0.79068186 0.07910345]

[[0.48877626 0.49253191 0.41638676 0.01444323 0.50608257]
 [0.90421954 0.09660544 0.43123235 0.09816755 0.43503765]]

[ 1.29214926  2.13295342  0.78791973 -0.12198653]

[0.31263766 0.66058798 0.95126668 0.60769637]

[9 5 5 4 9 4 5 8 7 7]


### **Arithmatic Operations**

In [24]:
#Arithmatic Operation in 1-D Arrays
var = np.array([1,2,3,4])
print(var + 3)   #direct addition
print(np.add(var,3))    #using add() of numpy module
print()
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = a + b
print(c)
print(np.add(a,b))

#Similarly we can use - * / % ** as subtract(),multiply(),divide(),mod(),power() respectively

[4 5 6 7]
[4 5 6 7]

[ 6  8 10 12]
[ 6  8 10 12]


In [25]:
#Arithmatic Operation in 2-D Arrays
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print()
b = np.array([[10,2,3,4],[15,6,7,1]])
print(b)
print()
c = np.add(a,b)
print(c)

[[1 2 3 4]
 [5 6 7 8]]

[[10  2  3  4]
 [15  6  7  1]]

[[11  4  6  8]
 [20 12 14  9]]


In [26]:
m = np.array([1,2,3,4,5])  #Multiplication with 3
print(m * 3)

[ 3  6  9 12 15]


In [27]:
x = np.array([-2,-1,0,1,2])
print(abs(x))            #absolute function
print(np.absolute(x))

[2 1 0 1 2]
[2 1 0 1 2]


In [29]:
a = np.arange(1,10).reshape(3,3)
print(a)
print()
print(np.fliplr(a))    #produces a mirror image -- left to right flipping
print()
print(np.flipud(a))    #produces a top down image -- up to down flipping
print()
print(a.transpose())   #produces a transpose matrix
print()
print(np.flipud(a.transpose()))
print()
print(np.rot90(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[3 2 1]
 [6 5 4]
 [9 8 7]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[3 6 9]
 [2 5 8]
 [1 4 7]]

[[3 6 9]
 [2 5 8]
 [1 4 7]]


### **Trigonometric Functions**

In [30]:
np.pi

3.141592653589793

In [31]:
theta = np.linspace(0,np.pi,5)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]
[ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16]


### **Exponential and Logarthmic Functions**

In [34]:
x = np.array([1,2,3,10])
print(x)
print(np.exp(x))   #[e**1,e**2,e**3,e**10]   where e=2.74)
print(np.exp2(x))  #[2**1,2**2,2**3,2**10]
print(np.power(x,3))  #print(x**3)
print(np.power(x,2))  #print(x**2)

[ 1  2  3 10]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 2.20264658e+04]
[   2.    4.    8. 1024.]
[   1    8   27 1000]
[  1   4   9 100]


In [35]:
print(np.log(x))     #log x
print(np.log2(x))
print(np.log10(x))

[0.         0.69314718 1.09861229 2.30258509]
[0.         1.         1.5849625  3.32192809]
[0.         0.30103    0.47712125 1.        ]


In [36]:
#Aggregate functions
x = np.array([1,2,3,4,5])
print(np.add.reduce(x))
print(np.add.accumulate(x))
print(np.subtract.reduce(x))
print(np.multiply.reduce(x))
print(np.multiply.accumulate(x))

15
[ 1  3  6 10 15]
-13
120
[  1   2   6  24 120]


### **Statistical Functions**

In [38]:
#Some statistical functions
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(np.min(a))  #Complete array
print(np.min(a,axis=0)) #Column wise
print(np.min(a,axis=1)) #Row wise
#Similarly np.max(a) can also be used

print()
print(np.min(a),np.max(a),np.argmin(a),np.argmax(a))  #argmin() -- gives the position of min element  #argmax() -- gives the position of max element
print(np.sqrt(a))   #Square root of array elements

[[1 2 3 4]
 [5 6 7 8]]
1
[1 2 3 4]
[1 5]

1 8 0 7
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]


In [42]:
import numpy as np
n = np.array([1,2,3,4,5,6,7,8,9])   #Statistical functions
print(np.max(n))
print(np.min(n))
print(np.sum(n))
print(np.mean(n))
print(np.median(n))
print(np.std(n))
print(np.var(n))
print(np.percentile(n,25))
print(np.percentile(n,50))
print(np.percentile(n,75))
print(np.percentile(n,100))

9
1
45
5.0
5.0
2.581988897471611
6.666666666666667
3.0
5.0
7.0
9.0


### **Shape and Re-Shape in Numpy Arrays**

In [43]:
arr1 = np.array([1,2,3,4],ndmin=4)
print(arr1)
print("Ndim:",arr1.ndim)       #ndim gives no of axis or dimensions of an array
print("Shape:",arr1.shape)     #Shape function gives the no of rows and columns in array
print()
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print("Ndim:",arr2.ndim)       #ndim gives no of axis or dimensions of an array
print("Shape:",arr2.shape)     #Shape function gives the no of rows and columns in array

[[[[1 2 3 4]]]]
Ndim: 4
Shape: (1, 1, 1, 4)

[[1 2 3 4]
 [5 6 7 8]]
Ndim: 2
Shape: (2, 4)


In [44]:
import numpy as np
a1 = np.array([1,2,3,4,5,6])
print(a1)
print(a1.ndim)
print()
a2 = a1.reshape(3,2)
print(a2)
print(a2.ndim)
print()
a3 = a1.reshape(2,3)
print(a3)
print(a3.ndim)
print()

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2

[[1 2 3]
 [4 5 6]]
2



In [46]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
#i = arr1.reshape((3,3))
i = np.reshape(arr1,(3,3))   #Re-shaping the 1-D to 3-D array
print(i)
print(i.ndim)
j = np.reshape(i,-1)   #Re-shaping the 3-D to 1-D array
print(j)
print(i.flatten())    #Re-shaping the 3-D to 1-D array using flatten method

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [47]:
u = np.array([1,2,3,4,5,6,7,8,9,10,11,12])   #Re-shaping the array
a1 = np.reshape(u,(4,3))
print(a1)
a2 = np.reshape(u,(2,3,2))
print(a2)
a3 = np.reshape(a2,-1)
print(a3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### **Broadcasting in Arrays**

In [48]:
x = np.array([[1],[2]])
print(x)
print(x.shape)   #(2,1)
print()
y = np.array([[1,2,3],[1,2,3]])
print(y)
print(y.shape)   #(2,3)
print()
# so there is 1 in RHS of shape in atleast one shapes between x and y
#addition is possible
z = x+y
print(z)
print(z.shape)   #max(x.shape,y.shape) -- (2,3)

[[1]
 [2]]
(2, 1)

[[1 2 3]
 [1 2 3]]
(2, 3)

[[2 3 4]
 [3 4 5]]
(2, 3)


In [49]:
x = np.array([1,2,3])
print(x)
print(x.shape)   #(1,3)
print()
y = np.array([[1],[2],[3]])
print(y)
print(y.shape)   #(3,1)
print()
# so there is 1 in RHS of shape in atleast one shapes between x and y
#addition is possible
z = x+y
print(z)
print(z.shape)   #max(x.shape,y.shape) -- (3,3)

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
(3, 3)


### **Slicing and Indexing**

In [50]:
arr1 = np.array([1,2,3,4])   #Indexing 1-D matrix
print(arr1)
print(arr1[0])

[1 2 3 4]
1


In [51]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])   #Indexing 2-D matrix
print(arr2)
print(arr2[0][2])
print(arr2[1][1])
print(arr2[0,1])

[[1 2 3 4]
 [5 6 7 8]]
3
6
2


In [54]:
p = np.array([[1,2,3,4],[5,6,7,8]])  #Indexing 2-D matrix
print(p)
print()
print(p[0,1])
print(p[1,2])
print(p[1,-1])
print(p[1,1:3])
print(p[0,1:3])
print(p[0:2,2])
print(p[0:2,1:3])

[[1 2 3 4]
 [5 6 7 8]]

2
7
8
[6 7]
[2 3]
[3 7]
[[2 3]
 [6 7]]


In [55]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])   #Indexing 3-D matrix
print(arr3)
print(arr3[0][1][1])
print(arr3[1][0][0])
print(arr3[0,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
5
3


In [56]:
k = np.arange(20)   #Slicing 1-D matrix
print(k)
print(k[1:10:2])

arr1 = np.array([1,2,3,4])   #Slicing 1-D matrix
print(arr1)
print(arr1[0:2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 3 5 7 9]
[1 2 3 4]
[1 2]


In [57]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])   #Slicing 2-D matrix
print(arr2)
print()
print(arr2[0,0:3])
print()
print(arr2[0:3,1])
print()
print(arr2[0:3,0:3])    #1st 3 rows and 1st 3 columns


l = np.array([[1,2,3], [3,4,5], [4,5,6]])   #Slicing sub-matrices
print(l)
print(l[0:2, 0:2]) #1st 2 rows and 1st 2 columns

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3]

[2 6]

[[1 2 3]
 [5 6 7]]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[1 2]
 [3 4]]


### **Iteration in Arrays**

In [58]:
v = np.array([[1,2,3],[4,5,6]])    #Iterating the 2-D Matrix -- no. of axis == no. of for loops
for x in v:
  for y in x:
    print(y)

1
2
3
4
5
6


In [59]:
w = np.array([[[1,2,3],[4,5,6],[7,8,9]]])   #Iterating the 3-D Matrix -- no. of axis == no. of for loops
for x in w:
  for y in x:
    for i in y:
      print(i)

1
2
3
4
5
6
7
8
9


In [60]:
v = np.array([[1,2,3],[4,5,6]])      #Iterating the 2-D Matrix
print(v)
for x in np.nditer(v):          #using nditer() we can avoid usage of multiple for loops
  print(x)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [62]:
v = np.array([[1,2,3],[4,5,6]])      #Iterating the 2-D Matrix
print(v)
for x in np.ndenumerate(v):          #using ndenumerate() we can avoid usage of multiple for loops and we can also its index also.
  print(x)

[[1 2 3]
 [4 5 6]]
((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((1, 0), 4)
((1, 1), 5)
((1, 2), 6)


### **Copy and view**

In [63]:
x = np.array([1,2,3,4])          #Copy() method
c = x.copy()
x[0] = 10
print(x)     #Original Array
print(c)     #Copy method doesn't get affected by the changes done to the original array

[10  2  3  4]
[1 2 3 4]


In [64]:
x = np.array([1,2,3,4])          #View() method
v = x.view()
x[0] = 10
print(x)     #Original Array
print(v)     #View method gets affected by the changes done to the original array

[10  2  3  4]
[10  2  3  4]


### **Functions in Arrays**

In [65]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.concatenate((a,b),axis=0)       #Adding as rows -- default
print(c)

[1 2 3 4 5 6 7 8]


In [66]:
s = np.array([[1,2],[3,4]])
t = np.array([[5,6]])
a = np.concatenate((s,t))
print(a)
a1 = np.concatenate((s,t),axis = 0)  #Adding as rows -- default
print(a1)
a2 = np.concatenate((s,t.T),axis = 1)  #Adding as columns   .T is nothing by transpose
print(a2)
a3 = np.concatenate((s,t),axis = None)  #Adding into single array
print(a3)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]


In [67]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a1 = np.stack((a,b),axis=0)       #Adding as rows -- default
print(a1)
a2 = np.stack((a,b),axis=1)       #Adding as columns -- default
print(a2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [68]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a2 = np.hstack((a,b))   #this works out when the no of rows are same
print(a2)
a3 = np.vstack((a,b))   #this works out when the no of columns are same
print(a3)
a4 = np.dstack((a,b))
print(a4)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [69]:
a = np.array([1,2,3,4])            #array_split()
print(a)
s = np.array_split(a,2)
print(s)
print(s[0])
print(s[0][0])

[1 2 3 4]
[array([1, 2]), array([3, 4])]
[1 2]
1


In [70]:
a = np.array([[1,2,3],[4,5,6]])    #array_split() is used to split the arrays
print(a)
s = np.array_split(a,2)
print(s)
print(s[0])
print(s[0][0])
print(s[0][0][0])

[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[[1 2 3]]
[1 2 3]
1


In [71]:
a = np.array([1,2,3,4,2,3,2])            #searching in array using where() function
x = np.where(a==1)
print(x)
y = np.where(a==2)
print(y)
z = np.where((a%2)==0)
print(z)

(array([0]),)
(array([1, 4, 6]),)
(array([1, 3, 4, 6]),)


In [72]:
a = np.array([1,2,3,4,6,7,8])
x = np.searchsorted(a,5)      #gives the position of passed element in searchsorted() function using search
print(x)

4


In [73]:
a = np.array([1,2,3,4,10,6,7,9,8])      #sorting
x = np.sort(a)
print(x)

b = np.array(['a','c','y','b'])
y = np.sort(b)
print(y)

[ 1  2  3  4  6  7  8  9 10]
['a' 'b' 'c' 'y']


In [74]:
a = np.array([[4,10,6],[5,1,0]])      #sorting
print(a)
x = np.sort(a,axis=1)       #row-wise
print(x)
y = np.sort(a,axis=0)       #column wise
print(y)

[[ 4 10  6]
 [ 5  1  0]]
[[ 4  6 10]
 [ 0  1  5]]
[[ 4  1  0]
 [ 5 10  6]]


In [76]:
a = np.array([1,2,3,4,10,6,7,9,8])    #shuffling the data in array
np.random.shuffle(a)
print(a)

[ 4  7  6  8  9  1 10  2  3]


In [77]:
a = np.array([1,2,3,4,10,6,1,2,3,4])     #deletes the duplicates
var = np.unique(a,return_index=True,return_counts=True)
print(var)

(array([ 1,  2,  3,  4,  6, 10]), array([0, 1, 2, 3, 5, 4]), array([2, 2, 2, 2, 1, 1]))


### **Insert and Delete elements in Array**

In [100]:
a = np.array([1,2,3,4])       #insert(arrayname,position/index no.,values)
v = np.insert(a,4,5)   #at position = 4
print(v)
v1 = np.insert(v,4,6.5)
print(v1)

[1 2 3 4 5]
[1 2 3 4 6 5]


In [103]:
a = np.array([1,2,3,4])       #append(arrayname,values) -- adds at the end
v = np.append(a,5)   #at position = 4
print(v)
v1 = np.append(a,6.5)
print(v1)

[1 2 3 4 5]
[1.  2.  3.  4.  6.5]


In [104]:
a = np.array([[1,2,3,4],[5,6,7,8]])
v = np.insert(a,2,5,axis=0)     #Row wise
print(v)
print()
v1 = np.insert(a,4,5,axis=1)    #Column wise
print(v1)

[[1 2 3 4]
 [5 6 7 8]
 [5 5 5 5]]

[[1 2 3 4 5]
 [5 6 7 8 5]]


In [105]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print()
v = np.insert(a,2,[9,10,11,12],axis = 0)     #Row wise
print(v)
print()
v1 = np.insert(a,4,[9,10],axis=1)    #Column wise
print(v1)

[[1 2 3 4]
 [5 6 7 8]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  9]
 [ 5  6  7  8 10]]


In [106]:
a = np.array([[1,2,3,4],[5,6,7,8]])     #append() without any index no. adds at the end
v = np.append(a,[[9,10,11,12]],axis=0)     #Row wise
print(v)
print()
v1 = np.append(a,[[9],[10]],axis=1)    #Column wise
print(v1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  9]
 [ 5  6  7  8 10]]


In [107]:
a = np.array([1,2,3,4])       #delete(arrayname,position/index no.)
v = np.delete(a,2)   #at position = 2 -- axis is also used
print(v)

[1 2 4]


In [108]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
v = np.delete(a,2,axis=1)  #column-wise
print(v)
v1 = np.delete(a,1,axis=0)    #row-wise
print(v1)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 4]
 [5 6 8]]
[[1 2 3 4]]


### **Matrices in Linear Algebra**

In [ ]:
help(np.linalg)

In [93]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(np.trace(m))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [81]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print(np.linalg.matrix_rank(a))
print('trace',np.trace(a))
print(np.linalg.det(a))
#print(np.linalg.inv(a))   only non-singular matrix are allowed ie., det!=0
#print(np.matmul(array1,array2))   matrix multiplication
print(np.linalg.matrix_power(a,3))   #a.a.a   matrix multiplication

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[2]
trace [1 2 3]
[0.]
[[[ 468  576  684]
  [1062 1305 1548]
  [1656 2034 2412]]]


### **Computational power between lists and numpy arrays**

In [78]:
import time

l1 = [i for i in range(1,10000)]
l2 = [i**2 for i in range(1,10000)]

#time consumed when used lists
t0 = time.time()
product_list = list(map(lambda x,y: x*y,l1,l2))
t1 = time.time()
time_product_list = t1-t0
print('time consumed by product_list :',time_product_list)


#time consumed when used numpy arrays
a1 = np.array(l1)
a2 = np.array(l2)
t0 = time.time()
product_array = a1*a2
t1 = time.time()
time_product_array = t1-t0
print('time consumed by product_array:',time_product_array)

#This is the reason why the numpy arrays are prefered over lists.

time consumed by product_list : 0.0036923885345458984
time consumed by product_array: 0.000213623046875


### **Examples**

4a + 2b + 5c = 53
5a + 3b + 7c = 74
9a + 2b + 6c = 73

find the value of a,b and c

In [ ]:
coeff = np.array ( [ [ 4, 2 , 5] , [ 5, 3, 7] , [9, 2, 6]] )
const = np.array ( [ 53 , 74, 73 ])
result = np.linalg.solve( coeff , const)
result

array([3., 8., 5.])


Day 1
6 macbooks and 3 iPhones were sold for rs 27

Day 2
9 macbooks and 4 iPhones were sold for rs 38

find the price of each macbook and iPhone

In [ ]:
# 6x + 3y = 27
# 9x + 4y = 38
# let us define coeff array
coeff = np.array (  [ [ 6,3] , [ 9, 4]] )
# define constants array
const = np.array  ( [ 27 , 38 ])

In [ ]:
# numpy provides np.linalg.solve( ) for solving equations
result = np.linalg.solve( coeff , const)
# value of x and y
result

array([2., 5.])

In [96]:
# x+5y-z=1
# 2x+3y-2z=2
#-3x+4y=0
#solve the equations and find x,y,z
coeff = np.array ( [ [ 1, 5 , -1] , [ 2, 3, -2] , [-3, 4, 0]] )
const = np.array ( [ 1,2,0 ])
result = np.linalg.solve(coeff , const)
result

array([-0.,  0., -1.])

In [98]:
a = np.array([[2,-1,-1],[2,-1,1],[4,-2,-3]])
b = np.array([1,0,-1])
print(np.linalg.solve(a,b))

LinAlgError: Singular matrix